Repository opensalt/opensalt, pull requests merged in 2018-05, with the labels that each got.

#435 Add underline button and function for the editor.
  app/Resources/assets/js/cftree/render-md.js
Labels: Area - Editor

#514 Add math equation button to WSIWYG
  app/Resources/assets/js/cftree/render-md.js
  app/Resources/assets/sass/styles.scss
  tests/_data/MarkdownFramework.json
  tests/_support/Page/Framework.php
  tests/acceptance/features/framework/organization_editor/markdown.feature
Labels: WYSIWYG

#509 Update issue templates
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: Review, Type - Enhancement
